# Generated by Django 5.0.3 on 2024-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
