# Generated by Django 5.0.3 on 2024-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_shippingaddress_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
